---
title: "Change log"
---

#### DCIEM_0.0.0.9001

-   Checks that i) TimeOut is after TimeIn, and ii) TimeIn is after the previous dive. If both are correct then "Add Entry" can be selected otherwise cannot be clicked (stops accidental entry of negative times ).
-   `AirOut` creates a red warning if \<30 bar and an orange warning if \<50 bar
-   Added `shinyjs` to disable submit button if `Time Out` \< `Time In` or `TimeIn` \< `TimeOut` from previous dive to avoid submitting invalid dives\\
-   `TimeOut` now updates when `TimeIn` is selected to make time entry easier

#### DCIEM_0.0.0.9000

-   Added base functions (`get_RG()`, `get_RF()`, `EAD()`)
-   Created base Shiny app "DCIEM log"
-   Added delete to remove rows

#### Future change list

-   Find a better way of handling where Shiny app resets if get_RG() throws a warning
-   Correctly handle updates of TimeIn to TimeOut on nrow()-1
-   Update so that factors (RF, RG, RG2, SI, RF) change dynamically when a row is deleted (fixed DCIEM_0.0.0.9001)?
-   Cells can currently be edited but only RG is updated dynamically
-   Find an approach to combining dives when \<15 minutes inline
